


<div class="contentEditor">
    <div id="dialogServerFile" class="editor files edefiles floatWin"
         style="display:none;">
        <form>
            <ul class="action-list"></ul>
        </form>
    </div>
</div>

<?php if ($this->r->module != 'publicms' && $this->r->controller != 'profile') { ?>
    <div id="containerAvatar" style="<?php if ($this->id <= 0) {
        echo 'display:none;';
    } ?>">
        <h2><?= Sydney_Tools_Localization::_('User\'s avatar') ?></h2>
        <fieldset id="dashboardAvatar">
            <a class="avatar" href="/adminpeople/index/editindex/id/<?php echo $this->id; ?>">
            <?php
            // Display avatar
            if ($p['avatar'] > 0) {
                $avatar = '/adminfiles/file/thumb/id/' . $p['avatar'] . '/ts/1/fn/' . $p['avatar'] . '.png';
                echo '<img width="64" height="64" class="img-circle" src="' . $avatar . '"/>';
            } else {
                echo '<i class="fa fa-user"></i>';
            }
            ?>
            </a>

            <a id="avatar-add" class="button" href="#"><img
                    src="<?php echo Sydney_Tools::getRootUrlCdn(); ?>/sydneyassets/images/ui/bigbutton/icon_<?php echo(($myavatar != Sydney_Tools::getUrlDefaultAvatar()) ? 'swap' : 'add'); ?>.png"></a>
            &nbsp;&nbsp;&nbsp;
            <a id="avatar-remove" class="button warning" href="#"
               style="<?php echo(($myavatar == Sydney_Tools::getUrlDefaultAvatar()) ? 'display:none;' : ''); ?>"><img
                    src="<?php echo Sydney_Tools::getRootUrlCdn(); ?>/sydneyassets/images/ui/bigbutton/icon_remove.png"></a>

            <div id="box-upload"
                 style="display: none; position: relative; margin-top: 65px;">
                <div style="padding: 8px 8px 20px 8px;">
                    Upload a
                    file<?php if ($this->r->module != 'publicms' && $this->r->controller != 'profile') { ?>,
                        <a class="bigbutton" id="browseServerButton"
                           href="javascript:return false;"
                           style="display: inline; float: none;"><?= Sydney_Tools_Localization::_('Browse the server') ?></a>
                    <?php } ?>
                    or <a id="fileCancel"
                          href="javascript: return false;"><?= Sydney_Tools_Localization::_('Cancel') ?></a>
                </div>
                <?php
                // browseButton
                echo $this->partial('index/upload.phtml', 'adminfiles', array(
                    'source'   => 'adminpeople',
                    'peopleid' => $this->id,
                    'request'  => $this->r
                ));
                ?>
            </div>
        </fieldset>
    </div>
<?php } ?>

<h2 class="formTitle"><?php
    if ($this->id) {
        echo Sydney_Tools::_("User's detail");
    } else {
        echo Sydney_Tools::_("Create account");
    }
    ?></h2>

<?php echo $this->usersForm; ?>

<input type="hidden" value="<?= $this->scriptParamModule;?>" id="script-module" />
<input type="hidden" value="<?= $this->scriptParamController;?>" id="script-controller" />
<input type="hidden" value="<?= $this->scriptParamId;?>" id="script-id" />
<input type="hidden" value="<?= $this->scriptParamRootCdn;?>" id="script-root-cdn" />