
<div id="peopdialog"></div>
<div class="sydney_editor_toolbar">
    <form class="form-horizontal" role="form">
        <div class="form-group col-sm-4">
            <label for="fstatus" class="col-sm-4 control-label"><?php echo Sydney_Tools_Localization::_('Status filter'); ?></label>
            <div class="col-sm-8">
                <select id="fstatus" name="fstatus" class="form-control">
                    <option
                        value=""><?php echo Sydney_Tools_Localization::_('All'); ?></option>
                    <option
                        value="1"><?php echo Sydney_Tools_Localization::_('Active'); ?></option>
                    <option
                        value="0"><?php echo Sydney_Tools_Localization::_('De-Activated'); ?></option>
                </select>
            </div>
        </div>
        <div class="form-group col-sm-4">
            <label for="fgroup" class="col-sm-4 control-label">Group filter</label>
            <div class="col-sm-8">
                <select id="fgroup" name="fgroup" class="form-control">
                    <option value="">All</option>
                    <?php foreach ($this->groups as $k => $v) : ?>
                        <option
                            value="<?php echo $k; ?>" <?php if (isset($this->r->fgroup) && $this->r->fgroup === (string)$k) {
                            echo 'selected';
                        } ?>><?php echo $v; ?></option>
                    <?php endforeach; ?>
                </select>
            </div>
        </div>
    </form>
</div>

<?php
$minfo = array(
    array(Sydney_Tools_Localization::_('Email'), 'login'),
    array(Sydney_Tools_Localization::_('Phone'), 'phone'),
);

$capsules = array(
    '<span class="capsule">' . Sydney_Tools_Localization::_('De-activated') . '</span>',
    ''
);

?>

<div class="col-sm-12">
    <ul class="pager">
        <li class="previous"><a href="#" id="prevbut-header">&larr; <?= Sydney_Tools_Localization::_('Previous items') ?></a></li>
        <div id="pagination-header"></div>
        <li class="next"><a href="#" id="nextbut-header"><?= Sydney_Tools_Localization::_('Next items') ?> &rarr;</a></li>
    </ul>
</div>


<div id="peoplelisting" class="col-sm-12">
    <div class="row">
    <?php foreach ($this->people as $p) : ?>
        <?php
        if (ucfirst($p['usersgroups_name']) == 'Developer'){
            $panelColor='primary';
        }
        elseif(ucfirst($p['usersgroups_name']) == 'Guest'){
            $panelColor='info';
        }
        elseif(ucfirst($p['usersgroups_name']) == 'Authuser'){
            $panelColor='warning';
        }
        elseif(ucfirst($p['usersgroups_name']) == 'Administrator'){
            $panelColor='danger';
        }
        elseif(ucfirst($p['usersgroups_name']) == 'Superadministrator'){
            $panelColor='red';
        }
        else{
            $panelColor='default';
        }; ?>
        <div class="userid<?php echo $p['id']; ?> col-lg-4">
        <div class="panel panel-<?php echo $panelColor; ?>">
            <div class="panel-heading">
                    <strong><?php echo $p['fname'] . ' ' . $p['lname']; ?></strong>
                    <?php echo $capsules[($p['active'])]; ?>
                    <span class="small"><?php echo ucfirst($p['usersgroups_name']); ?></span>
            </div>
            <div class="panel-body">
                <div class="col-lg-3">
                <button class="btn btn-<?php echo $panelColor; ?> btn-circle btn-xl" type="button">
                    <?php
                    // Display avatar
                    if ($p['avatar'] > 0) {
                        $avatar = '/adminfiles/file/thumb/id/' . $p['avatar'] . '/ts/1/fn/' . $p['avatar'] . '.png';
                        echo '<img width="64" height="64" class="img-circle" src="' . $avatar . '"/>';
                    } else {
                        echo '<i class="fa fa-user"></i>';
                    }
                    ?>
                </button>
                </div>
                <div class="col-lg-8">
                    <div>
                        <?php foreach ($minfo as $m): ?>
                            <?php
                            $val = $p[($m[1])];
                            if ($val != '' && $val != '0'):
                                ?>
                                <p class="text-<?= $panelColor?>">
                                    <label><?php echo $m[0]; ?></label>
                                    <?php echo $val; ?>
                                </p>
                            <?php endif; ?>
                        <?php endforeach; ?>
                    </div>
                </div>
            </div>
            <div class="panel-footer">
                    <a class="btn btn-primary"
                       href="/adminpeople/index/profile/id/<?php echo $p['id']; ?>"><i class="fa fa-info fa-fw"></i> View details</a>
                    <a class="btn btn-success"
                       href="/adminpeople/index/editindex/id/<?php echo $p['id']; ?>"><i class="fa fa-edit fa-fw"></i> Edit</a>
                    <?php if ($this->users_id != $p['id']) { ?>
                        <a class="btn btn-danger" href="/adminpeople/services/delete/id/<?php echo $p['id']; ?>/format/json"><i class="fa fa-trash-o fa-fw"></i>Delete</a>
                    <?php } ?>
            </div>
        </div>
    </div>
    <?php endforeach; ?>
</div>

<input type="hidden" value="<?= $this->scriptParamEmbed;?>" id="script-embed" />
<input type="hidden" value="<?= $this->scriptParamContext;?>" id="script-context" />
<input type="hidden" value="<?= $this->scriptParamFilter;?>" id="script-filter" />
<input type="hidden" value="<?= $this->scriptParamMode;?>" id="script-mode" />
