<?php echo $this->addiScript; ?>
<?php if ($this->embed && !$this->ckeditor_context): ?>
    <p class="buttons col-lg-12">
        <a class="btn btn-success" href="save"><?= Sydney_Tools_Localization::_('Save as actual content') ?></a>
        <a class="btn btn-info" href="save-draft"><?= Sydney_Tools_Localization::_('Save as draft') ?></a>
        <a class="btn btn-default" href="cancel"><?= Sydney_Tools_Localization::_('Cancel') ?></a>
    </p>
<?php endif; ?>

<div class="dialogConvertCls"></div>

<div id="fileEdit"></div>
<div id="filesBrowse">
    <div class="sydney_editor_toolbar">
        <form class="form-horizontal" role="form">
            <div class="col-lg-4">
                <div class="btn-group">
                    <button class="active btn btn-default" style="width:40px">
                        <a id="thumbviewb"  title="Thumbnails" href="#"><i class="fa fa-th"></i></a>
                    </button>
                    <button class="btn btn-default" style="width:40px">
                        <a id="listviewb" title="List" href="#"><i class="fa fa-list"></i></a>
                    </button>
                </div>
                <div class="btn-group">
                    <button class="active btn btn-default" style="width:40px">
                        <a id="thumbviewb"  title="Thumbnails" href="#"><i class="fa fa-image"></i></a>
                    </button>
                    <button class="btn btn-default" style="width:40px">
                        <a id="listviewb" title="List" href="#"><i class="fa fa-folder"></i></a>
                    </button>
                </div>
                <div class="btn-group ui-toolbar-item-filter">
                    <button class ="btn btn-primary" type="button" id="createfoldbtn">
                        <i class="fa fa-plus fa-fw"></i> <i class="fa fa-folder"></i>
                    </button>
                </div>
            </div>
            <div class="form-group col-lg-4">
                <label class="col-lg-4 control-label" for="sortBy1"><?= Sydney_Tools_Localization::_('Sort by') ?></label>
                <div class="col-lg-8">
                    <select id="sortBy1" class="form-control">
                        <option><?= Sydney_Tools_Localization::_('Last modified') ?></option>
                        <option><?= Sydney_Tools_Localization::_('Name') ?></option>
                    </select>
                </div>
            </div>
            <div class="form-group col-lg-4">
                <label class="col-lg-4 control-label ui-toolbar-item-filter" for="sortBy2"><?= Sydney_Tools_Localization::_('Filter') ?></label>
                <div class="col-lg-8">
                    <select id="sortBy2" class="form-control">
                        <option value="-">-</option>
                    </select>
                </div>
                <a class="ui-toolbar-smartquery-toggle fladvfilter"
                   title="Advanced filter" href="#">
                    <img
                        src="<?php echo $this->cdnurl; ?>/sydneyassets/images/ui/toolbar/smartquery.png"
                        border="0"/>
                </a>
                <div class="advfilfiltersbox"></div>
            </div>
        </form>
        <div id="butselection" class="col-lg-12"><?= Sydney_Tools_Localization::_('selection') ?></div>
        <div class="col-lg-12">
            <div class="pager">
                <li class="previous"><a href="#" id="prevbut-header">&larr; <?= Sydney_Tools_Localization::_('Previous items') ?></a></li>
                <div id="pagination-header"></div>
                <li class="next"><a href="#" id="nextbut-header"><?= Sydney_Tools_Localization::_('Next items') ?> &rarr;</a></li>
            </div>
        </div>


        <div id="pagination-header">
        </div>

    <div id="filelisting" class="filelistscroll"></div>

    <?php if ($this->embed && !$this->ckeditor_context): ?>
            <div class="col-lg-12">
                <div class="pager">
                    <li class="previous"><a href="#" id="prevbut-footer">&larr; <?= Sydney_Tools_Localization::_('Previous items') ?></a></li>
                    <div id="pagination-header"></div>
                    <li class="next"><a href="#" id="nextbut-footer"><?= Sydney_Tools_Localization::_('Next items') ?> &rarr;</a></li>
                </div>
            </div>
            <div id="pagination-footer"></div>
    <?php endif; ?>
</div>


<input type="hidden" value="<?= $this->scriptParamEmbed;?>" id="script-embed" />
<input type="hidden" value="<?= $this->scriptParamContext;?>" id="script-context" />
<input type="hidden" value="<?= $this->scriptParamFilter;?>" id="script-filter" />
<input type="hidden" value="<?= $this->scriptParamMode;?>" id="script-mode" />
<input type="hidden" value="<?= $this->scriptParamId;?>" id="script-id" />
<input type="hidden" value="<?= $this->scriptParamQuery;?>" id="script-query" />