<?php
/**
 * Displays the HTML for the structure of folders (category tagging)
 *
 * @param $s
 * @return string
 */
function _HTMLfolderStructure($s)
{
    global $catcntr;
    $html = '';
    foreach ($s as $e) {
        $catcntr++;
        if (isset($e['id']) && $e['label']) {
            for ($i = 0; $i <= $catcntr; $i++) {
                $html .= '&nbsp;&nbsp;&nbsp;&nbsp;';
            }
            $html .= ' <input type="checkbox" name="catids[]" value="' . $e['id'] . '"> ' . $e['label'] . '<br/>' . "\n";
        }
        if ($e['kids']) {
            $html .= _HTMLfolderStructure($e['kids']);
        }
        $catcntr--;
    }
    return $html;
}
$catcntr = 0;
?>
<a class="btn btn-primary"><i class="fa fa-reply fa-fw"></i> Back</a>
<form method="post" action="#">
    <div class="catcontainer">
        <div class="col-lg-offset-10">
            <a class="btn btn-lg btn-default" href="categoryButton"><i class="fa fa-link fa-fw"></i> Link to category</a>
        </div>
        <div
            class="categoryPlaceholder"><?= _HTMLfolderStructure($this->categories); ?></div>
    </div>

    <div id="uploader">
        <p><?= Sydney_Tools_Localization::_('Your browser doesn\'t have Flash, Silverlight or HTML5 support.') ?></p>
    </div>

    <div style="clear: both"></div>

</form>
<div id="log"></div>
<?php if (!isset($this->source) || $this->source != 'adminpeople') : ?>
    <div id="folderreldiv"></div>
<?php endif; ?>

<input type="hidden" value="<?= $this->scriptParamSource;?>" id="script-source" />
<input type="hidden" value="<?= $this->scriptParamPeopleId;?>" id="script-peopleid" />
<input type="hidden" value="<?= $this->scriptParamModule2;?>" id="script-module" />
<input type="hidden" value="<?= $this->scriptParamMaxSize;?>" id="script-maxsize" />
<input type="hidden" value="<?= $this->scriptParamRootCdn2;?>" id="script-root-cdn" />