<?php
/**
 * Displays the HTML for the structure of folders (category tagging)
 *
 * @param $s
 * @return string
 */
function _HTMLfolderStructure($s)
{
    global $catcntr;
    $html = '';
    foreach ($s as $e) {
        $catcntr++;
        if (isset($e['id']) && $e['label']) {
            for ($i = 0; $i <= $catcntr; $i++) {
                $html .= '&nbsp;&nbsp;&nbsp;&nbsp;';
            }
            $html .= ' <input type="checkbox" name="catids[]" value="' . $e['id'] . '"> ' . $e['label'] . '<br/>' . "\n";
        }
        if ($e['kids']) {
            $html .= _HTMLfolderStructure($e['kids']);
        }
        $catcntr--;
    }

    return $html;
}

$catcntr = 0;

?><!-- Load the queue CSS -->
<style
    type="text/css">@import url(<?=Sydney_Tools_Paths::getRootUrlCdn();?>/sydneyassets/jslibs/jquery/plugins/plupload/plupload.queue.css);</style>


<!-- Load plupload and all it's runtimes and finally the jQuery queue widget -->
<script type="text/javascript"
        src="<?= Sydney_Tools_Paths::getRootUrlCdn(); ?>/sydneyassets/jslibs/jquery/plugins/plupload/plupload.full.min.js"></script>
<script type="text/javascript"
        src="<?= Sydney_Tools_Paths::getRootUrlCdn(); ?>/sydneyassets/jslibs/jquery/plugins/plupload/jquery.plupload.queue.min.js"></script>

<style>
    div.catcontainer {
        padding: 10px;
    }

    div.catcontainer div.categoryPlaceholder {
        border: 1px solid #AAA;
        background-color: #FFF;
        padding-top: 10px;
        padding-bottom: 10px;
    }
</style>
<form method="post" action="#">
    <div class="catcontainer">
        <a href="categoryButton">Link to category</a>

        <div
            class="categoryPlaceholder"><?= _HTMLfolderStructure($this->categories); ?></div>
    </div>

    <div id="uploader" style="height: 330px;">
        <p><?= Sydney_Tools_Localization::_('Your browser doesn\'t have Flash, Silverlight or HTML5 support.') ?></p>
    </div>

    <div style="clear: both"></div>

</form>
<div id="log"></div>
<?php if (!isset($this->source) || $this->source != 'adminpeople') : ?>
    <div id="folderreldiv"></div>
<?php endif; ?>

<input type="hidden" value="<?= $this->scriptParamSource;?>" id="script-source" />
<input type="hidden" value="<?= $this->scriptParamPeopleId;?>" id="script-peopleid" />
<input type="hidden" value="<?= $this->scriptParamModule2;?>" id="script-module" />
<input type="hidden" value="<?= $this->scriptParamMaxSize;?>" id="script-maxsize" />
<input type="hidden" value="<?= $this->scriptParamRootCdn2;?>" id="script-root-cdn" />