<?php
$lostpass = false;
$register = false;

$translate = Zend_Registry::get('Zend_Translate');

$linkregister = '/default/login/register/';
$textregister = $translate->_('Not a member yet?');

if (isset($this->config->login)) {
    if (isset($this->config->login->lostpassword) && $this->config->login->lostpassword) {
        $lostpass = true;
    }
    if (isset($this->config->login->register) && $this->config->login->register != '') {
        $register = true;
    }
    if (isset($this->config->login->linkregister) && $this->config->login->linkregister != '') {
        $linkregister = $this->config->login->linkregister;
    }
    if (isset($this->config->login->textregister) && $this->config->login->textregister != '') {
        $textregister = $this->config->login->textregister;
    }
}

$errors = $this->form->getDescription();
if ($errors) {
    ?>
    <div id="effortErrors" class="topError" style="display: block;">
        <ul>
            <li><?php echo $errors; ?></li>
        </ul>
    </div>
<?php
}
?>


<div class="container">
    <div class="row">
        <div class="col-md-4 col-md-offset-4">
            <div class="login-panel panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title"><?php if (isset($this->errormessage) && $this->errormessage != '') { ?>
                            <div class="errormessage"><?php echo $this->errormessage; ?></div>
                        <?php } ?></h3>
                </div>
                <div class="panel-body">
                            <div id="flContent">
                                <?php echo $this->form; ?>

                                <?php
                                if (($lostpass || $register) && !$this->adminmodule) {
                                ?>
                            </div>
                            <ul class="ulLoginOptions">
                                <?php if ($lostpass) { ?>
                                    <li>
                                        <a href="/default/login/lostpassword/"><?= $translate->_('Lost password?'); ?></a>
                                    </li>
                                <?php
                                }
                                if ($register) {
                                    ?>
                                    <li>
                                        <a href="<?php echo $linkregister; ?>"><?= $translate->_($textregister); ?></a>
                                    </li>
                                <?php } ?>
                            </ul>
                            <?php
                            }
                            ?>
                </div>
            </div>
        </div>
    </div>
</div>





