<?php
if (isset($this->sydneylayout) && $this->sydneylayout == 'no') {
    $nolayout = true;
} else {
    $nolayout = false;
}

if (!isset($this->vmode)) {
    $this->vmode = 'thumb';
}
if (isset($this->files)) {
    $files = $this->files;
} else {
    $files = array();
}

if (isset($this->nbpages)) {
    $nbpages = $this->nbpages;
} else {
    $nbpages = 0;
}

$minfo = array(
    array('Email', 'email'),
    array('Phone', 'phone'),
);

$capsules = array(
    '<span class="capsule">De-activated</span>',
    ''
);


?>


<script>
    var gblnumpages = <?php echo $nbpages; ?>;
    $(function () {
        // detail dialog
        $('#peopdialog').dialog(
            {
                'autoOpen': false,
                'height': 400,
                'width': 665,
                'title': 'User\'s info',
                'buttons': {
                    "Ok": function () {
                        $(this).dialog("close");
                    }
                }
            }
        );
        $('.vdetailb').click(function (e) {
            e.preventDefault();
            var url = $(this).attr('href');
            $('#peopdialog').dialog('open').html('Loading...').load(url + '/sydneylayout/no');
        });
        // delete buttons
        $('.peodeleteb').click(function (e) {
            e.preventDefault();
            var url = $(this).attr('href');
            if (confirm('Are you sure you want to delete this user?\nYou can not undo this action...\nAre you really sure?')) {
                $('#ajaxbox').msgbox({'message': 'Loading...', 'showtime': 0, 'modal': true});
                $.getJSON(url, {}, function (o, u) {
                    if (u == 'success') {
                        $('#ajaxbox').msgbox(o.ResultSet);
                        if (o.ResultSet.status == 1) {
                            $('.userid' + o.ResultSet.id).slideUp();
                        }
                    }
                });
            }
        });

    });
</script>





<?php if (is_array($this->people) && count($this->people) > 0) : ?>
    <?php foreach ($this->people as $p) : ?>
        <?php
        if (ucfirst($p['usersgroups_name']) == 'Developer'){
            $panelColor='primary';
        }
        elseif(ucfirst($p['usersgroups_name']) == 'Guest'){
            $panelColor='info';
        }
        elseif(ucfirst($p['usersgroups_name']) == 'Authuser'){
            $panelColor='warning';
        }
        elseif(ucfirst($p['usersgroups_name']) == 'Administrator'){
            $panelColor='danger';
        }
        elseif(ucfirst($p['usersgroups_name']) == 'Superadministrator'){
            $panelColor='red';
        }
        else{
            $panelColor='default';
        }; ?>
        <div class="userid<?php echo $p['id']; ?> col-lg-4">
            <div class="panel panel-<?php echo $panelColor; ?>">
                <div class="panel-heading">
                    <strong><?php echo $p['fname'] . ' ' . $p['lname']; ?></strong>
                    <?php echo $capsules[($p['active'])]; ?>
                    <span class="small"><?php echo ucfirst($p['usersgroups_name']); ?></span>
                </div>
                <div class="panel-body">
                    <div class="col-lg-3">
                        <button class="btn btn-<?php echo $panelColor; ?> btn-circle btn-xl" type="button">
                            <?php
                            // Display avatar
                            if ($p['avatar'] > 0) {
                                $avatar = '/adminfiles/file/thumb/id/' . $p['avatar'] . '/ts/1/fn/' . $p['avatar'] . '.png';
                                echo '<img width="64" height="64" class="img-circle" src="' . $avatar . '"/>';
                            } else {
                                echo '<i class="fa fa-user"></i>';
                            }
                            ?>
                        </button>
                    </div>
                    <div class="col-lg-8">
                        <div>
                            <?php foreach ($minfo as $m): ?>
                                <?php
                                $val = $p[($m[1])];
                                if ($val != '' && $val != '0'):
                                    ?>
                                    <p class="text-<?= $panelColor?>">
                                        <label><?php echo $m[0]; ?></label>
                                        <?php echo $val; ?>
                                    </p>
                                <?php endif; ?>
                            <?php endforeach; ?>
                        </div>
                    </div>
                </div>
                <div class="panel-footer">
                    <a class="btn btn-primary vdetailb"
                       href="/adminpeople/index/profile/id/<?php echo $p['id']; ?>"><i class="fa fa-info fa-fw"></i> View details</a>
                    <a class="btn btn-success"
                       href="/adminpeople/index/editindex/id/<?php echo $p['id']; ?>"><i class="fa fa-edit fa-fw"></i> Edit</a>
                    <?php if ($this->users_id != $p['id']) { ?>
                        <a class="btn btn-danger peodeleteb" href="/adminpeople/services/delete/id/<?php echo $p['id']; ?>/format/json"><i class="fa fa-trash-o fa-fw"></i>Delete</a>
                    <?php } ?>
                </div>
            </div>
        </div>
    <?php endforeach; ?>
    <?php else : ?>
        <strong><?php echo Sydney_Tools_Localization::_('No Users with those filters.'); ?></strong>
<?php endif; ?>

<div class="filepropdialog"></div>