
<table class="table">
    <thead>
    <tr>
        <th>Id</th>
        <th>Domain</th>
        <th>Label</th>
        <th>Creation date</th>
        <th>Action</th>
    </tr>
    </thead>
    <?php foreach($this->webinstances as $webinstance): ?>
        <tr>
            <td><?= $webinstance->id ;?></td>
            <td><?= $webinstance->domain ;?></td>
            <td><?= $webinstance->label ;?></td>
            <td><?= $webinstance->creationdate ;?></td>
            <td>
                <a class="btn btn-xs btn-primary" href="/adminglobal/index/editsafinstances/id/<?= $webinstance->id ?>"><i class="fa fa-edit fa-fw"></i> Edit</a>
                <a class="btn btn-xs btn-danger" href="/adminglobal/services/editsafinstances/format/json/id/<?= $webinstance->id ?>"><i class="fa fa-times fa-fw"></i> Delete</a>
            </td>
        </tr>
    <?php endforeach ?>
</table>

<h4 class="text-primary pull-right">
    Manage your webinstances
</h4>