<table class="table">
    <thead>
    <tr>
        <th>Id</th>
        <th>Status</th>
        <th>Description</th>
    </tr>
    </thead>
    <?php foreach($this->userGroups as $group): ?>
        <tr>
            <td><?= $group->id ;?></td>
            <td><?= $group->name ;?></td>
            <td><?= $group->desc ;?></td>
        </tr>
    <?php endforeach ?>
</table>
<h4 class="text-primary pull-right">
    Manage your groups
</h4>