<?php
if (isset($this->layout()->avmodules[($this->layout()->currentModule)])) {
    $mdn = $this->layout()->currentModule;
}
else {
    $mdn = 'default';
}
$pprops = $this->layout()->avmodules[$mdn];
$trans = $this->layout()->translate;
$settingsNms = new Zend_Session_Namespace('appSettings');
?>
<!DOCTYPE html>
<html lang="en">
	<head>
        <meta charset="utf-8" />
		<?php echo $this->headTitle(); ?>
		<script type="text/javascript">
            var sydneyadmin=true;
            var current_instance = <?php echo $this->safinstances_id; ?>;
            var applicationLanguage	= "<?php echo $settingsNms->ApplicationLanguage; ?>";
            var _ENV = "<?= Sydney_Tools_Sydneyglobals::getConf('general')->env ?>";
		</script>

		<?php echo $this->headStyle(); ?>
		<?php echo $this->headScript(); ?>
		<?php echo $this->headLink(); ?>

        <!-- Bootstrap Core CSS -->
        <link href="sydneyassets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

        <!-- Custom CSS -->
        <link href="sydneyassets/vendor/sb-admin/css/sb-admin-2.css" rel="stylesheet">

        <!-- Custom Fonts -->
        <link href="sydneyassets/vendor/font-awesome-4.1.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">

        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
        <![endif]-->
	</head>
<body id="<?php echo $pprops[4]; ?>">
    <div id="wrapper">
        <nav class="navbar navbar-default navbar-static-top" style="margin-bottom: 0" role="navigation">

            <div class="navbar-header">
                <button class="navbar-toggle" data-target=".navbar-collapse" data-toggle="collapse" type="button">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/"><?= $this->layout()->_config->general->siteTitle; ?></a>
            </div>
            <ul class="nav navbar-top-links navbar-right">
                <li class="dropdown">
                    <a class="dropdown-toggle" href="#" data-toggle="dropdown">
                        <i class="fa fa-language fa-fw"></i>
                        <i class="fa fa-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-language">
                        <li>
                            <a href="/admindashboard/?slang=en">
                                EN
                            </a>
                        </li>
                        <li>
                            <a href="/admindashboard/?slang=fr">
                                FR
                            </a>
                        </li>
                        <li>
                            <a href="/admindashboard/?slang=nl">
                                NL
                            </a>
                        </li>
                    </ul>
                </li>
                <li class="dropdown">
                    <a class="dropdown-toggle" href="#" data-toggle="dropdown">
                        <i class="fa fa-user fa-fw"></i>
                        <i class="fa fa-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-user">
                        <li>
                            <a href="/adminpeople/index/editindex/id/<?= $this->layout()->users_id; ?>/">
                                <i class="fa fa-user fa-fw"></i>
                                <?= $this->layout()->auth->getIdentity(); ?>
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="/default/login/logout">
                                <i class="fa fa-sign-out fa-fw"></i>
                                Logout
                            </a>
                        </li>
                    </ul>
                </li>
            </ul>

            <div role="navigation" class="navbar-default sidebar">
                <div class="sidebar-nav navbar-collapse">
                    <ul id="side-menu" class="nav">
                        <?php if ($this->layout()->search): ?>
                            <li class="sidebar-search">
                                <div class="input-group custom-search-form">
                                    <div id="search">
                                        <input id="searchinput"  type="text" placeholder="Search..." class="form-control" />
                                        <input id="searchcontext" type="hidden" value="<?php echo $this->moduleName; ?>"/>
                                        <span class="input-group-btn">
                                            <button type="button" class="btn btn-default">
                                                <i class="fa fa-search"></i>
                                            </button>
                                        </span>
                                    </div>
                                </div>
                                <!-- /input-group -->
                            </li>
                        <?php endif; ?>
                        <?php
                        if ($this->layout()->auth->hasIdentity()) {

                            foreach($this->layout()->avmodules as $mname => $mprop){
                                $cssClass = '';
                                if( (isset($this->emodule) && 'admin'.$this->emodule == $mname ) || $this->layout()->currentModule == $mname){
                                    $cssClass = 'active';
                                }

                                if ($mprop[1] && Sydney_Accessright::isAuthorized2module(null, $mname)){
                                    ?>
                                    <li>
                                        <a href="/<?= $mname; ?>" class="<?= $cssClass;?>">
                                            <i class="fa fa-<?= $mprop[3];?> fa-fw"></i>
                                                <?= $trans->_($mprop[0]); ?>
                                        </a>
                                    </li>
                                <?php
                                }
                            }
                        }
                        ?>

                    <li>

                    </li>

                </ul>
            </div>
            <!-- /.sidebar-collapse -->
        </div>
        </nav>













        <div id="page-wrapper">
            <div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header"><?php echo $trans->_($pprops[2]); ?></h1>
                    <?php echo $this->layout()->content; ?>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
        </div>


    </div>



    <?php
    /* !!!!  MAEL A NE PAS RETIRER MAEL  !!!!
    if (isset($this->layout()->sidebaraction)) {
        $sba = $this->layout()->sidebaraction;
    } else {
        $sba = array('index','index', 'adminsidebars');
    }
    if ($this->layout()->auth->hasIdentity()) {
        echo $this->action($sba[0], $sba[1], $sba[2]);
    } else {
        echo $this->action('sidebar', 'login', 'default');
    }*/
    ?>
    <div class="footer_version">
        Zend Framework <?= Zend_Version::VERSION ?> / PHP <?= PHP_VERSION ?>
    </div>

    <!-- jQuery Version 1.11.0 -->
    <script src="sydneyassets/vendor/jquery/js/jquery-1.11.0.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="sydneyassets/vendor/bootstrap/js/bootstrap.min.js"></script>

    <!-- Metis Menu Plugin JavaScript -->
    <script src="sydneyassets/vendor/metis-menu/js/metisMenu.min.js"></script>

    <!-- Custom Theme JavaScript -->
    <script src="sydneyassets/vendor/sb-admin/js/sb-admin-2.js"></script>

</body>
</html>
