<!DOCTYPE html>
<html xml:lang="en" xmlns="http://www.w3.org/1999/xhtml">
	<head>
        <meta charset="utf-8" />
		<title>Sydney::Login</title>
		<?php echo $this->headTitle(); ?>
		<?php echo $this->headStyle(); ?>

		<?php echo $this->headLink(); ?>

        <!-- Bootstrap Core CSS -->
        <link href="<?= Sydney_Tools::getRootUrlCdn();?>/sydneyassets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

        <!-- Custom CSS -->
        <link href="<?= Sydney_Tools::getRootUrlCdn();?>/sydneyassets/vendor/sb-admin/css/sb-admin-2.css" rel="stylesheet">

        <!-- Custom Fonts -->
        <link href="<?= Sydney_Tools::getRootUrlCdn();?>/sydneyassets/vendor/font-awesome-4.1.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">

        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
        <![endif]-->
	</head>

<body>

	<div id="sectionbar" class="col-sm-12">
		<?php echo $this->layout()->content; ?>
	</div>

    <!-- jQuery Version 1.11.0 -->
    <script src="<?= Sydney_Tools::getRootUrlCdn();?>/sydneyassets/vendor/jquery/js/jquery-1.11.0.js"></script>

    <?php echo $this->headScript(); ?>
</body>
</html>

