<?php
/**
 * index_create view
 * @package Adminpages
 * @subpackage View
 */

$n = null;
if ($this->parentid && !$this->node) {
} // echo 'add under this parentid';
else if ($this->parentid === null && !$this->node) {
} // echo 'add at the end';
else if ($this->node) {
    $n = $this->node; // edit mode
    $this->parentid = $n->parent_id;
}
?>

<form action="/adminpages/index/editprocess" method="post" class="styled-form">

    <input type="hidden" name="id" value="<?php if ($n && $n->id) {
        echo $n->id;
    } ?>"/>

    <div class="form-group">
        <label
            for="label"><?= Sydney_Tools_Localization::_('Page title') ?></label>

        <input type="text" id="label" name="label" class="form-control"
               value="<?php if ($n && $n->label) {
                   echo $this->escape($this->nodeTranslate->_($n->id, $n->label));
               } ?>"/>
        <span
            class="help-block"><?= Sydney_Tools_Localization::_('For example: About, Contact, ...') ?></span>
    </div>

    <div class="form-group">
        <label
            for="htmltitle"><?= Sydney_Tools_Localization::_('Page title tag') ?></label>

        <input type="text" id="htmltitle" name="htmltitle" class="form-control"
               value="<?php if ($n && $n->htmltitle) {
                   echo $this->escape($this->nodeTranslate->_($n->id, $n->htmltitle, 'htmltitle'));
               } ?>"/>
        <span
            class="help-block"><?= Sydney_Tools_Localization::_('About page title tag') ?></span>
    </div>

    <div class="form-group">
        <label for="url"><?= Sydney_Tools_Localization::_('Url') ?></label>


        <div class="input-group">
            <span class="input-group-addon">
                http://<?= trim($_SERVER['HTTP_HOST'], '/') ?>/
            </span>
            <input
                class="form-control input-inline" type="text"
                id="url" name="url"
                value="<?php if ($n && $n->url) {
                    echo $this->escape($this->nodeTranslate->_($n->id, $n->url, 'url'));
                } ?>"/>
        </div>
    </div>

    <div class="form-group">
        <label
            for="parentPage"><?= Sydney_Tools_Localization::_('Parent page') ?></label>

        <select id="parent_id" name="parent_id" class="form-control">
            <?php echo $this->StructureDropdown()->setStructureArray($this->structureArray)->setSelectedId($this->parentid); ?>
        </select>

        <span
            class="help-block"><?= Sydney_Tools_Localization::_('The main category for this page.') ?></span>
    </div>

    <div class="form-group">
        <label class="checkbox-inline" for="ishome">
            <input type="checkbox" id="ishome" name="ishome"
                   value="1" <?php if ($n && $n->ishome && $n->ishome == 1) {
                echo 'checked';
            } ?>/>
            <?= Sydney_Tools_Localization::_('Set this page as website') ?> <?= Sydney_Tools_Localization::_('Homepage') ?>
        </label>
    </div>


    <div class="form-group">
        <label
            for="usersgroups_id"><?= Sydney_Tools_Localization::_('Access rights') ?></label>

        <select id="usersgroups_id" name="usersgroups_id" class="form-control">
            <?php foreach ($this->usersgroups as $k => $usrg): ?>
                <option
                    value="<?php echo $k; ?>" <?php if ($n && $n->usersgroups_id && $n->usersgroups_id == $k) {
                    echo "selected";
                } ?> ><?php echo $usrg; ?></option>
            <?php endforeach; ?>
        </select>
        <span
            class="help-block"><?= Sydney_Tools_Localization::_('The group of users which could access this page and its children.') ?></span>
    </div>


    <div class="buttonsbox">
        <input type="submit" name="createPage" class="btn btn-lg btn-primary"
               value="<?= Sydney_Tools_Localization::_('Save') ?>"/>
        <a class="btn btn-lg btn-default" href="/adminpages"><?= Sydney_Tools_Localization::_('Cancel') ?></a>
    </div>

</form>